version: "3.5"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=localhost
#     volumes:
#       - crawl_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: "Carrefour_crawl_db"