version: "3.5"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=local2
#     volumes:
#       - crawl_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: "Carrefour_crawl_db"